### ISSUE TITLE
F & D extensions

### ISSUE THREAD

**Issue by kalairajah** [riscv/riscv-ovpsim#17]
Hi,
 I have a few testcases with floating point instructions and when running through OVPSim, I get the following Warning ..

Warning (RISCV_ADF) CPU 'riscvOVPsim/cpu' 0x... ... fsqrt.s fa4, ft4: Illegal Instruction - extension F (single-precision floating point) absent or inactive.

I'm invoking ovpsim using the following command ..
riscvOVPSim.exe -- variant R64G --program <.elf> 

I tried with the --override riscvOVPSim/cpu/addExtensions=FD to the above command, but still get the above warning.

What am I missing here to get teh FP isntructions through ovpsim?

Thanks,
Kalai

**Comment by jstraus59** [comment]
Hi Kalai,

This is due to the the mstatus.fs field as defined by the RISCV architecture. This field resets to 0 and  application code should set this to a non-zero value to enable floating point operations.

Alternatively you can use a simulation command line parameter to override the reset value for this field, as explained in the [Model Specific Information for RV64G](http://www.ovpworld.org/model-specific-documentation-for-risc-v-riscv64-rv64g) referred to in the [doc/README.md](https://github.com/riscv/riscv-ovpsim/blob/master/doc/README.md) file:

> By default, the processor starts with floating-point instructions disabled (mstatus.FS=0). Use parameter "mstatus_FS" to force mstatus.FS to a non-zero value for floating-point to be enabled from the start.

**Comment by kalairajah** [comment]
Thanks Jim. It is working fine now.
