### ISSUE TITLE
License conflict

### ISSUE THREAD

**Issue by aka-sps** [riscv/riscv-ovpsim#30]
Which of the licenses for this project is valid?
Proprietary license from LICENSE.pdf (revocable and time limited) or http://www.apache.org/licenses/LICENSE-2.0 from source files?

**Comment by simon5656** [comment]
On the website in the README it says
License: Model source included under Apache 2.0 open source license
License: Simulator riscvOVPsim licensed under Open Virtual Platforms (OVP) Fixed Platform Kits license

so the is simulator etc is under the LICENSE.pdf
and the model source is under Apache 2.0

________________________________

**Comment by aka-sps** [comment]
So, has the license expired on June 13, 2019 or not?

**Comment by simon5656** [comment]
Sorry, I dont understand. If you download the current riscvOVPsim, are you saying there is a problem?
thanks

________________________________

**Comment by aka-sps** [comment]
> Imperas grants to Licensee, a nonexclusive, nontransferable right to use the Software for a period
> of one year from the date of this release or until the Software expires (if earlier).

Date of "this release": June 13, 2018.
There is no other way to determine the release date.

**Comment by jstraus59** [comment]
Have you tried downloading the [latest release](https://github.com/riscv/riscv-ovpsim/releases/tag/v20191113.0)?

**Comment by simon5656** [comment]
The LICENSE.pdf has a creation date of May 2018 - that is when the document was created - it is the document's date - not the software license.

The github README has a date/version in, for example:
Date : 22 Nov 2019 Version: 20191122.0

that is the software version.

The LICENSE.pdf states: "for a period of one year from the date of this release or until the Software expires (if earlier)" - so that means you have a license to use the software for one year or until the software expires - one year from 22 Nov 2019... i.e. until 22 Nov 2020 or earlier if the software expires earlier...

The reasoning is to ensure users make use of current features etc.

If I clone from the github repo and
cd riscv-ovpsim/bin/Linux64

and type:
riscvOVPsim.exe --version

I get the version:
20191122.0

and when I type:
riscvOVPsim.exe --showexpiry

I get the expiry date:
Info (PER_DDR) 177 License days remain (expires on 20 May 2020)


So I am not sure where the confusion is
If you are using a version dated June 13, 2018, then yes it will have expired and please download the latest version.

thanks

________________________________

**Comment by aka-sps** [comment]
It is difficult to determine what relates to a “simulator, etc.,” and what relates to a model code.
Could you split the code with different types of licenses into different submodules?
Also add missing licenses for third-party components (such as ActiveState).

Thank you!

**Comment by simon5656** [comment]
I am sorry but I cant seem to understand what is wrong.

The model source is written in ASCII in C and is the source directory and in the files it says they are covered by the Apache 2.0 license.

The simulator etc is an x86 binary and is in the bin directory. The simulator is only delivered as a binary and is covered by the license in LICENSE.pdf

ActiveState would not help here.

Thank you for your interest in riscvOVPsim - and please let us know when you have issues in running it.


________________________________

**Comment by aka-sps** [comment]
No license notice for some third-party components

For example:

riscv-ovpsim/bin/Windows64/tcl85.dll
> Version language : English (US)
      FileDescription	: Tcl DLL
      OriginalFilename	: tcl85.dll
      CompanyName	: ActiveState Corporation
      FileVersion	: 8.5.11
      LegalCopyright	: Copyright © 2001 by ActiveState Corporation, et al
      ProductName	: Tcl 8.5 for Windows
      ProductVersion	: 8.5.11

riscv-ovpsim/bin/Windows64/pthreadGC2-w64.dll
> Version language : English (US)
      FileDescription	: POSIX Threads for Windows Library
      ProductVersion	: 2, 9, 0, 0
      FileVersion	: 2, 9, 0, 0
      InternalName	: pthreadGC
      OriginalFilename	: pthreadGC
      CompanyName	: Open Source Software community project
      LegalCopyright	: Copyright (C) Project contributors 1998-2004
      Licence	: LGPL
      Info	: http://sources.redhat.com/pthreads-win32/
      Comment	: GNU C build -- longjmp thread exiting

**Comment by simon5656** [comment]
Thanks for pointing this out. These have now been resolved and the repo  bin directory includes text files with the appropriate licenses.

________________________________
