### ISSUE TITLE
compile v extension

### ISSUE THREAD

**Issue by wyahiaoui** [riscv/riscv-ovpsim#7]
I am actually working on the risc V ISA where I want to make optimization through the V-Extension.  

I began with the examples, I checked the source code where inline assembly is used to invoke the vectors instruction. As next step, I wanted to develop my application using the simd instruction where I built some simple vectors operation in the goal to get familiar with the instructions. I compiled using 
- riscv64-unkown-elf-gcc -march=rv64gcv -mabi=ilp64d -o hello_world hello_world.c

But I get unrecognized substring. I updated the toolchain many times, I deleted it and reintalled it again but it doesn't bring any result. 

When I remove the march and abi, I get the unrecognized opcode.

Can you please help me to compile the V Instruction with the risc v gcc toolchain

**Comment by jeremybennett** [comment]
Hi @wyahiaoui,

There is no support for the vector instruction set in either GCC or LLVM.  The problem is that the V extension is large (bigger than all other extensions combined) and complex, so adding it to any compiler is a big (=expensive) job. I believe there are versions of binutils with some assembler support for V extensions.

My company (which is a compiler company) is trying to move this forward, by building a consortium to invest in this work.

**Comment by duncangraham-Imperas** [comment]
I am afraid that there currently is no cross compiler that I am aware of that supports the vector instructions.

The example vector instruction elf files that are provided with riscvOVPsim were compiled using a combination of C compiler and binutils from different sources.

**Comment by jstraus59** [comment]
The examples were built using the assembler from the [SiFive binutils rvv branch](https://github.com/sifive/riscv-binutils-gdb/tree/rvv). This is the only place I am aware of that supports using _-march=rv64gcv_
